### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by KaruroChori**
Reference: https://github.com/ionutrogojan/grouchy/issues/1

### CODE REVIEW

**Review by ionutrogojan — COMMENTED** [review]
Could you please comment with your operating system and browser choice. I need to understand if this is an OS issue or browser issue because there is a css property already active `image-rendering: pixelated;` which works on Chromium based browsers. Maybe different browsers interpret that property differently. Thank you :)

**Comment by KaruroChori** [comment]
Firefox 88.0.1 linux-amd64.
This is a "documented" difference of this browser as far as I tell but not really a bug
https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

I totally missed that you had a line above with the same directive already set to pixelated. I should not write PR during nighttime.
As it stands this cannot be merged without conflicting with chromium: I am closing this.

**Comment by KaruroChori** [comment]
I just figured my current release was 1 year old. It seems like they fixed it to the behaviour shown by chromium in the meanwhile.
I tested it now and it works as expected.

**Comment by ionutrogojan** [comment]
No problem man, thanks for showing interest in the project and trying to improve. Feel free to modify the project to fit your needs and request new features!

**Pull request closed without merging**
